In [1]:
import polars as pl
from pathlib import Path

In [2]:
SCRIPT_DIR = Path(".").absolute().resolve()
DATA_DIR = (SCRIPT_DIR.parent / "data").absolute().resolve()
PROCESSED_DATA_DIR = (SCRIPT_DIR.parent / "processed").absolute().resolve()

print(f"{DATA_DIR=}")
print(f"{PROCESSED_DATA_DIR=}")
assert DATA_DIR.is_dir()
assert PROCESSED_DATA_DIR.is_dir()

DATA_DIR=PosixPath('/Users/Naot/kristal-thesis-not-mine/data')
PROCESSED_DATA_DIR=PosixPath('/Users/Naot/kristal-thesis-not-mine/processed')

In [3]:
financials_df = pl.read_parquet(PROCESSED_DATA_DIR / "financials.parquet")
financials_df

shape: (12_488, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ l_tradepa ┆ l_tradere ┆ equity    ┆ l_rec     ┆ … ┆ netprofit ┆ CA        ┆ s_rec     ┆ s_tradep │
│ y         ┆ c         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ay       │
│ ---       ┆ ---       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ ---      │
│ i64       ┆ i64       ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 596387094 ┆ 822972692 ┆ … ┆ 309193823 ┆ 568158024 ┆ 120488821 ┆ 51738186 │
│           ┆           ┆ 0230      ┆ 78        ┆   ┆ 134       ┆ 8153      ┆ 1832      ┆ 7012     │
│ 0         ┆ 0         ┆ 202635778 ┆ 0         ┆ … ┆ 703150885 ┆ 173748814 ┆ 138444809 ┆ 58880617 │
│           ┆           ┆ 918       ┆           ┆   ┆           ┆ 806       ┆ 98        ┆ 28       │
│ 0         ┆ 0         ┆ 707621123 ┆ 314441647 ┆ … ┆ -24665762 ┆ 468060301 ┆ 417455201 ┆ 31694531 │
│           ┆           ┆ 065       ┆ 42        ┆   ┆ 99        ┆ 717       ┆ 374       ┆ 405      │
│ 0         ┆ 0         ┆ 779898572 ┆ 422895499 ┆ … ┆ -17328079 ┆ 668923956 ┆ 652037971 ┆ 83408012 │
│           ┆           ┆ 112       ┆ 6         ┆   ┆ 341       ┆ 357       ┆ 396       ┆ 21       │
│ 0         ┆ 0         ┆ 316138316 ┆ 228335464 ┆ … ┆ 309824052 ┆ 174258791 ┆ 396400964 ┆ 33134340 │
│           ┆           ┆ 256       ┆ 4         ┆   ┆ 15        ┆ 993       ┆ 45        ┆ 993      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0         ┆ 0         ┆ 249300052 ┆ 0         ┆ … ┆ 685726393 ┆ 259028204 ┆ 108801209 ┆ 18558366 │
│           ┆           ┆ 895       ┆           ┆   ┆ 30        ┆ 803       ┆ 22        ┆ 02       │
│ 0         ┆ null      ┆ 512188997 ┆ 0         ┆ … ┆ -79905479 ┆ 524956713 ┆ 124508136 ┆ 47689612 │
│           ┆           ┆ 251       ┆           ┆   ┆ 135       ┆ 017       ┆ 945       ┆ 6        │
│ 0         ┆ 0         ┆ 237028091 ┆ 0         ┆ … ┆ 527787849 ┆ 263023258 ┆ 672520501 ┆ 10185196 │
│           ┆           ┆ 529       ┆           ┆   ┆ 4         ┆ 443       ┆ 38        ┆ 4772     │
│ 0         ┆ 0         ┆ 158477431 ┆ 115178638 ┆ … ┆ 921475208 ┆ 236047690 ┆ 125626044 ┆ 48904908 │
│           ┆           ┆ 418       ┆           ┆   ┆ 3         ┆ 370       ┆ 859       ┆ 319      │
│ 0         ┆ 0         ┆ 102121673 ┆ 142710971 ┆ … ┆ -38281112 ┆ 115618766 ┆ 407282549 ┆ 14663441 │
│           ┆           ┆ 1588      ┆ 95        ┆   ┆ 8518      ┆ 9446      ┆ 273       ┆ 2414     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
icb_df = pl.read_parquet(PROCESSED_DATA_DIR / "icb.parquet")
icb_df

shape: (732, 6)
┌────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ ticker ┆ icb1            ┆ icb2            ┆ icb3            ┆ icb4            ┆ icb5            │
│ ---    ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             │
│ str    ┆ str             ┆ str             ┆ str             ┆ str             ┆ str             │
╞════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ AAA    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ AAM    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Nuôi trồng thủy │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ hải sản         │
│ AAT    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
│ ABR    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ ┆ Tư vấn & Hỗ trợ │
│        ┆                 ┆ Công nghiệp     ┆ Kinh doanh      ┆ KD              ┆ KD              │
│ ABS    ┆ Hàng Tiêu dùng  ┆ Thực phẩm và đồ ┆ Sản xuất thực   ┆ Nuôi trồng nông ┆ Trồng ngũ cốc,  │
│        ┆                 ┆ uống            ┆ phẩm            ┆ & hải sản       ┆ rau, trái cây   │
│        ┆                 ┆                 ┆                 ┆                 ┆ &…              │
│ …      ┆ …               ┆ …               ┆ …               ┆ …               ┆ …               │
│ VTV    ┆ Công nghiệp     ┆ Xây dựng và Vật ┆ Xây dựng và Vật ┆ Vật liệu xây    ┆ Vật liệu xây    │
│        ┆                 ┆ liệu            ┆ liệu            ┆ dựng & Nội thất ┆ dựng khác       │
│ VTZ    ┆ Nguyên vật liệu ┆ Hóa chất        ┆ Hóa chất        ┆ Nhựa, cao su &  ┆ Nhựa            │
│        ┆                 ┆                 ┆                 ┆ sợi             ┆                 │
│ WCS    ┆ Công nghiệp     ┆ Hàng & Dịch vụ  ┆ Vận tải         ┆ Kho bãi, hậu    ┆ Bến xe khách    │
│        ┆                 ┆ Công nghiệp     ┆                 ┆ cần và bảo      ┆                 │
│        ┆                 ┆                 ┆                 ┆ dưỡng           ┆                 │
│ WSS    ┆ Tài chính       ┆ Dịch vụ tài     ┆ Dịch vụ tài     ┆ Môi giới chứng  ┆ Môi giới chứng  │
│        ┆                 ┆ chính           ┆ chính           ┆ khoán           ┆ khoán           │
│ X20    ┆ Hàng Tiêu dùng  ┆ Hàng cá nhân &  ┆ Hàng cá nhân    ┆ Hàng May mặc    ┆ Hàng May mặc    │
│        ┆                 ┆ Gia dụng        ┆                 ┆                 ┆                 │
└────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [10]:
cleaned_financials_df = (
    financials_df.join(
        icb_df,
        on="ticker",
        how="left",
        validate="m:1",
    )
    .filter(pl.col("icb2").is_not_null())
    .filter(
        ~pl.col("icb2").is_in(
            [
                "Dịch vụ tài chính",
                "Ngân hàng",
                "Bảo hiểm",
            ]
        )
    )
    .filter(~pl.col("ticker").is_in(["DSC", "MIC"]))
    .sort(["ticker", "year"])
    .with_columns(
        [
            pl.col("TA").log().alias("SIZE"),
            (pl.col("mktcap") / pl.col("equity")).alias("MTB"),
            (pl.col("TL") / pl.col("TA")).alias("LEVRG"),
            (pl.col("netprofit") / pl.col("TA")).alias("ROA"),
        ]
    )
)
cleaned_financials_df

ColumnNotFoundError: unable to find column "year"; valid columns: ["l_tradepay", "l_traderec", "equity", "l_rec", "TA", "s_traderec", "sellingexp", "cfo", "div", "cash", "sales", "NCL", "cogs", "dep", "GAexp", "CL", "operatingprofit", "ppe", "ebt", "grossprofit", "NCA", "inventory", "RE", "exchange", "ticker", "TL", "netsales", "netprofit", "CA", "s_rec", "s_tradepay", "icb1", "icb2", "icb3", "icb4", "icb5"]